In [7]:
# Actividad Autónoma
# Manipulación Avanzada de Arreglos con NumPy
# Resolución de tres ejercicios prácticos

import numpy as np


## Ejercicio 1: Cambiar los valores impares de un arreglo a -1


print("=== Ejercicio 1 ===")
# Crear un arreglo del 0 al 19
arr = np.arange(20)
print("Arreglo original:")
print(arr)

# Cambiar los valores impares por -1 usando indexación booleana
arr_modificado = arr.copy()
arr_modificado[arr_modificado % 2 == 1] = -1
print("Arreglo con impares reemplazados por -1:")
print(arr_modificado)

# Prueba adicional
arr2 = np.arange(10, 30)
arr2[arr2 % 2 == 1] = -1
print("Prueba con nuevo arreglo:")
print(arr2)



=== Ejercicio 1 ===
Arreglo original:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Arreglo con impares reemplazados por -1:
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]
Prueba con nuevo arreglo:
[10 -1 12 -1 14 -1 16 -1 18 -1 20 -1 22 -1 24 -1 26 -1 28 -1]


In [8]:

## Ejercicio 2: Convertir un arreglo 1D de 16 elementos a 4x4


print("\n=== Ejercicio 2 ===")
# Crear un arreglo 1D de 16 elementos
arr_1d = np.arange(16)
print("Arreglo 1D:")
print(arr_1d)

# Convertir a una matriz 4x4 usando reshape
matriz_4x4 = arr_1d.reshape((4, 4))
print("Matriz 4x4:")
print(matriz_4x4)

# Prueba adicional con otro rango
otra_matriz = np.arange(100, 116).reshape((4, 4))
print("Otra matriz 4x4:")
print(otra_matriz)



=== Ejercicio 2 ===
Arreglo 1D:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Matriz 4x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Otra matriz 4x4:
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]]


In [9]:

## Ejercicio 3: Concatenar dos matrices horizontal y verticalmente


print("\n=== Ejercicio 3 ===")
# Crear dos matrices 2x3
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

print("Matriz A:")
print(A)
print("Matriz B:")
print(B)

# Concatenación horizontal (axis=1)
concat_h = np.concatenate((A, B), axis=1)
print("Concatenación horizontal:")
print(concat_h)

# Concatenación vertical (axis=0)
concat_v = np.concatenate((A, B), axis=0)
print("Concatenación vertical:")
print(concat_v)

# Prueba adicional con matrices 3x2
C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8], [9, 10], [11, 12]])

print("Otra concatenación horizontal:")
print(np.concatenate((C, D), axis=1))

print("Otra concatenación vertical:")
print(np.concatenate((C, D), axis=0))


=== Ejercicio 3 ===
Matriz A:
[[1 2 3]
 [4 5 6]]
Matriz B:
[[ 7  8  9]
 [10 11 12]]
Concatenación horizontal:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Concatenación vertical:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Otra concatenación horizontal:
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]
Otra concatenación vertical:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
